#!/bin/sh
raco link cs2500-client
raco pack --collect --at-plt ++setup cs2500-client cs2500-client.plt cs2500-client 
raco link -r cs2500-client
rsync -avz cs2500-client.plt wilbowma@login.ccs.neu.edu:/course/cs2500sp14/.www/cs2500-client.plt
